name: delete-old-workflow-runs

on: [push]

jobs:
  delete-workflow-runs:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    name: A job to delete workflow runs
    steps:
      - name: Delete workflow runs
        uses: MajorScruffy/delete-workflow-runs@v0.1.0
        id: delete-workflow-runs
        with:
          repository: PipecraftNet/v2hot.github.io
          # workflow: ".github/workflows/main.yml"
          # 10 days
          older-than-seconds: 864000
          # created-before: "2021-12-08T16:34:00Z"
          # actor: test@test.com
          # branch: main
          # event: push
          # event: completed
          # maximum-workflow-runs-to-keep: 0
          what-if: 0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
